# Generated by Django 4.2.1 on 2023-06-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageTable',
        ),
        migrations.AlterField(
            model_name='interpretations',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testov.image'),
        ),
    ]
