# Generated by Django 4.2.1 on 2023-06-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
