# Generated by Django 4.2.1 on 2023-06-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
