# Generated by Django 4.2.1 on 2023-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretations',
            name='image',
            field=models.ImageField(null=True, upload_to='files/covers'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
