# Generated by Django 4.2.1 on 2023-06-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0002_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokens',
            old_name='token',
            new_name='token1',
        ),
    ]
