# Generated by Django 4.2.1 on 2023-06-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0002_remove_answers_image_remove_questions_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='right',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='interpretations',
            name='image',
            field=models.ImageField(null=True, upload_to='files/covers'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testov.answers'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='mixq',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='obligatory',
            field=models.BooleanField(),
        ),
    ]
