# Generated by Django 4.2.1 on 2023-06-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0002_rename_image_imagetable_alter_interpretations_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTable',
            new_name='Image',
        ),
    ]
