# Generated by Django 4.2.1 on 2023-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0002_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretations',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
