# Generated by Django 4.2.1 on 2023-05-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0002_answers_interpretations_questions_subtest_tast_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atemption',
            new_name='Attemption',
        ),
    ]
