# Generated by Django 4.2.1 on 2023-06-11 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testov', '0003_rename_imagetable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretations',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testov.image'),
        ),
    ]
